### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by A3shTnT** [sunlex0717/DissectingTensorCores#1]
Hello, I have a lot of compilation errors when compiling the program of the sm_70 architecture, and the compilation prompt requires an architecture of sm_75 or higher. So what configuration should I modify? My cuda version is 10.2

**Comment by sunlex0717** [comment]
Hi:

Some mma instructions are not supported by Volta Architecture (SM_70). So the compiler will trigger errors with those instructions. Actually,  Volta Architecture usually works with legacy wmma instructions. We explain the differences of wmma and mma instructions in our paper.
For more technical details, you may also check PTX ISA document (https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#warp-level-matrix-instructions).

**Comment by A3shTnT** [comment]
Yes, I know the difference between the wmma instruction and the mma instruction from the article, but I see in the readme that related configurations of the Volta architecture can be set. In order to test the delay of the tensor core instruction of the Volta architecture, I try to modify the mma instruction in the cu file and change them to the wmma instruction. Is this correct? Or whether you have a more convenient way to modify or related documents.Thank you!

**Comment by sunlex0717** [comment]
We did not implement wmma here. you can extend the micro-benchmarking by adding wmma instructions, following the programming guidance of PTX document. 

If you want to dive into Volta Tensor Cores. I would recommend this paper(https://arxiv.org/abs/1811.08309). It presents an in-depth analysis of Volta Tensor Core.

**Comment by A3shTnT** [comment]
Ok I know,and thank you. Raiden Shogun fan.
