### ISSUE TITLE
error: identifier "CLK_FREQUENCY" is undefined

### ISSUE THREAD

**Issue by MicroZHY** [sunlex0717/DissectingTensorCores#2]
when I complie the project, it shows the error like "error: identifier "CLK_FREQUENCY" is undefined",please tell me how to fix it ? thks!

**Comment by ZuohongJiang** [comment]
with same error.

**Comment by MicroZHY** [comment]
您好！您的邮件已收悉，谢谢常联系哦饮水思源

**Comment by hudengjunai** [comment]
Hello， have you solved this problem? Can you provide a docker container ?> 您好！您的邮件已收悉，谢谢常联系哦饮水思源

**Comment by hudengjunai** [comment]
I have encountered the same problem.

**Comment by hudengjunai** [comment]
change to MEM_xx solve the problem. but 
initialize_fake_metadata_2_4 where is this function?

**Comment by fan1997** [comment]
I meet the same problem initialize_fake_metadata_2_4

**Comment by MicroZHY** [comment]
您好！您的邮件已收悉，谢谢常联系哦饮水思源

**Comment by brilliant-yan** [comment]
Hello， have you solved this problem? Can you provide workaround? 
Thks.

**Comment by MicroZHY** [comment]
您好！您的邮件已收悉，谢谢常联系哦饮水思源

**Comment by sunlex0717** [comment]
Hi:

Sorry for the late response. 

I missed some setting files when upload this repo which includes initialize_fake_metadata_2_4 and CLK_FREQUENCY.

For initialize_fake_metadata_2_4 , the following is original implementation:


```
// note this is just fake meta data, used for performance microbenchmarking
void initialize_fake_metadata_2_4(uint32_t* metadata, int row_size,int col_size){
  int range = 6;
  uint32_t FourToTwoMeta[6] = {0x4, 0x8, 0x9, 0xc, 0xd, 0xe};
  for(int i = 0; i < row_size * col_size/16;i++){ // 32 bit can represent 16 indexes , each index has 2 bit
      uint32_t result = 0x0;
      for (int n = 0; n < 32 / 4; ++n) {
        double rnd = double(std::rand()) / double(RAND_MAX);
        rnd = range * rnd;
        uint32_t meta = FourToTwoMeta[(int)rnd];

        result = (uint32_t)(result | ((uint32_t)(meta << (i * 4))));
    }
    metadata[i] = result;
  }
}
```

For CLK_FREQUENCY, you can add define based on your GPU settings,
Sorry for the inconvenience of late reply
Good luck

**Comment by MicroZHY** [comment]
您好！您的邮件已收悉，谢谢常联系哦饮水思源

**Comment by MicroZHY** [comment]
Thank you! I would like to ask you one more question: How should we set the value of "CLK_FREQUENCY"?

**Comment by MicroZHY** [comment]
> Hi:
> 
> Sorry for the late response.
> 
> I missed some setting files when upload this repo which includes initialize_fake_metadata_2_4 and CLK_FREQUENCY.
> 
> For initialize_fake_metadata_2_4 , the following is original implementation:
> 
> ```
> // note this is just fake meta data, used for performance microbenchmarking
> void initialize_fake_metadata_2_4(uint32_t* metadata, int row_size,int col_size){
>   int range = 6;
>   uint32_t FourToTwoMeta[6] = {0x4, 0x8, 0x9, 0xc, 0xd, 0xe};
>   for(int i = 0; i < row_size * col_size/16;i++){ // 32 bit can represent 16 indexes , each index has 2 bit
>       uint32_t result = 0x0;
>       for (int n = 0; n < 32 / 4; ++n) {
>         double rnd = double(std::rand()) / double(RAND_MAX);
>         rnd = range * rnd;
>         uint32_t meta = FourToTwoMeta[(int)rnd];
> 
>         result = (uint32_t)(result | ((uint32_t)(meta << (i * 4))));
>     }
>     metadata[i] = result;
>   }
> }
> ```
> 
> For CLK_FREQUENCY, you can add define based on your GPU settings, Sorry for the inconvenience of late reply Good luck

Thank you! I would like to ask you one more question: How should we set the value of "CLK_FREQUENCY"?

**Comment by sunlex0717** [comment]
You can either add 
`#define CLK_FREQUENCY = xxxxx; // (you should find the xxMhz in your GPU settings).`

or add it as a compiler tag. But add a line of #define CLK_FREQUENCY = xxxxx in a common xx.h file would be the quickest solution.

**Comment by MicroZHY** [comment]
您好！您的邮件已收悉，谢谢常联系哦饮水思源
